export default {
    mockDataAllLeaders: [
        {
            id: 1,
            name: 'Nguyen Van A',
            country: 'Vietnam',
            countryCode: 'vn',
            avatar: 'https://www.w3schools.com/howto/img_avatar.png',
        },
        {
            id: 2,
            name: 'John',
            country: 'Vietnam',
            countryCode: 'vn',
            avatar: 'https://www.w3schools.com/howto/img_avatar.png',
        },
        {
            id: 3,
            name: 'John Even',
            country: 'China',
            countryCode: 'cn',
            avatar: 'https://www.w3schools.com/howto/img_avatar.png',
        },
        {
            id: 4,
            name: 'Obama',
            country: 'USA',
            countryCode: 'us',
            avatar: 'https://www.w3schools.com/howto/img_avatar.png',
        }
    ],
    mockDataLeaderByCountries: {
        vn: [
            {
                id: 1,
                name: 'Nguyen Van A',
                country: 'Vietnam',
                countryCode: 'vn',
                avatar: 'https://www.w3schools.com/howto/img_avatar.png',
            },
            {
                id: 2,
                name: 'John',
                country: 'Vietnam',
                countryCode: 'vn',
                avatar: 'https://www.w3schools.com/howto/img_avatar.png',
            },
        ],
        cn: [
            {
                id: 3,
                name: 'John Even',
                country: 'China',
                countryCode: 'cn',
                avatar: 'https://www.w3schools.com/howto/img_avatar.png',
            }
        ],
        us: [
            {
                id: 4,
                name: 'Obama',
                country: 'USA',
                countryCode: 'us',
                avatar: 'https://www.w3schools.com/howto/img_avatar.png',
            }
        ]
    },
    mockDataLeaderId: '5b05972dda959130aeaa0124',
    mappingCountryCodeToName: {
        ad: 'Andorra',
        ae: 'United Arab Emirates',
        af: 'Afghanistan',
        ag: 'Antigua and Barbuda',
        ai: 'Anguilla',
        al: 'Albania',
        am: 'Armenia',
        ao: 'Angola',
        ap: 'Asia/Pacific Region',
        aq: 'Antarctica',
        ar: 'Argentina',
        as: 'American Samoa',
        at: 'Austria',
        au: 'Australia',
        aw: 'Aruba',
        ax: 'Aland Islands',
        az: 'Azerbaijan',
        ba: 'Bosnia and Herzegovina',
        bb: 'Barbados',
        bd: 'Bangladesh',
        be: 'Belgium',
        bf: 'Burkina Faso',
        bg: 'Bulgaria',
        bh: 'Bahrain',
        bi: 'Burundi',
        bj: 'Benin',
        bl: 'Saint Bartelemey',
        bm: 'Bermuda',
        bn: 'Brunei Darussalam',
        bo: 'Bolivia',
        bq: 'Bonaire, Saint Eustatius and Saba',
        br: 'Brazil',
        bs: 'Bahamas',
        bt: 'Bhutan',
        bv: 'Bouvet Island',
        bw: 'Botswana',
        by: 'Belarus',
        bz: 'Belize',
        ca: 'Canada',
        cc: 'Cocos (Keeling) Islands',
        cd: 'Congo, The Democratic Republic of the',
        cf: 'Central African Republic',
        cg: 'Congo',
        ch: 'Switzerland',
        ci: "Cote d'Ivoire",
        ck: 'Cook Islands',
        cl: 'Chile',
        cm: 'Cameroon',
        cn: 'China',
        co: 'Colombia',
        cr: 'Costa Rica',
        cu: 'Cuba',
        cv: 'Cape Verde',
        cw: 'Curacao',
        cx: 'Christmas Island',
        cy: 'Cyprus',
        cz: 'Czech Republic',
        de: 'Germany',
        dj: 'Djibouti',
        dk: 'Denmark',
        dm: 'Dominica',
        do: 'Dominican Republic',
        dz: 'Algeria',
        ec: 'Ecuador',
        ee: 'Estonia',
        eg: 'Egypt',
        eh: 'Western Sahara',
        er: 'Eritrea',
        es: 'Spain',
        et: 'Ethiopia',
        eu: 'Europe',
        fi: 'Finland',
        fj: 'Fiji',
        fk: 'Falkland Islands (Malvinas)',
        fm: 'Micronesia, Federated States of',
        fo: 'Faroe Islands',
        fr: 'France',
        ga: 'Gabon',
        gb: 'United Kingdom',
        gd: 'Grenada',
        ge: 'Georgia',
        gf: 'French Guiana',
        gg: 'Guernsey',
        gh: 'Ghana',
        gi: 'Gibraltar',
        gl: 'Greenland',
        gm: 'Gambia',
        gn: 'Guinea',
        gp: 'Guadeloupe',
        gq: 'Equatorial Guinea',
        gr: 'Greece',
        gs: 'South Georgia and the South Sandwich Islands',
        gt: 'Guatemala',
        gu: 'Guam',
        gw: 'Guinea-Bissau',
        gy: 'Guyana',
        hk: 'Hong Kong',
        hm: 'Heard Island and McDonald Islands',
        hn: 'Honduras',
        hr: 'Croatia',
        ht: 'Haiti',
        hu: 'Hungary',
        id: 'Indonesia',
        ie: 'Ireland',
        il: 'Israel',
        im: 'Isle of Man',
        in: 'India',
        io: 'British Indian Ocean Territory',
        iq: 'Iraq',
        ir: 'Iran, Islamic Republic of',
        is: 'Iceland',
        it: 'Italy',
        je: 'Jersey',
        jm: 'Jamaica',
        jo: 'Jordan',
        jp: 'Japan',
        ke: 'Kenya',
        kg: 'Kyrgyzstan',
        kh: 'Cambodia',
        ki: 'Kiribati',
        km: 'Comoros',
        kn: 'Saint Kitts and Nevis',
        kp: "Korea, Democratic People's Republic of",
        kr: 'Korea, Republic of',
        kw: 'Kuwait',
        ky: 'Cayman Islands',
        kz: 'Kazakhstan',
        la: "Lao People's Democratic Republic",
        lb: 'Lebanon',
        lc: 'Saint Lucia',
        li: 'Liechtenstein',
        lk: 'Sri Lanka',
        lr: 'Liberia',
        ls: 'Lesotho',
        lt: 'Lithuania',
        lu: 'Luxembourg',
        lv: 'Latvia',
        ly: 'Libyan Arab Jamahiriya',
        ma: 'Morocco',
        mc: 'Monaco',
        md: 'Moldova, Republic of',
        me: 'Montenegro',
        mf: 'Saint Martin',
        mg: 'Madagascar',
        mh: 'Marshall Islands',
        mk: 'Macedonia',
        ml: 'Mali',
        mm: 'Myanmar',
        mn: 'Mongolia',
        mo: 'Macao',
        mp: 'Northern Mariana Islands',
        mq: 'Martinique',
        mr: 'Mauritania',
        ms: 'Montserrat',
        mt: 'Malta',
        mu: 'Mauritius',
        mv: 'Maldives',
        mw: 'Malawi',
        mx: 'Mexico',
        my: 'Malaysia',
        mz: 'Mozambique',
        na: 'Namibia',
        nc: 'New Caledonia',
        ne: 'Niger',
        nf: 'Norfolk Island',
        ng: 'Nigeria',
        ni: 'Nicaragua',
        nl: 'Netherlands',
        no: 'Norway',
        np: 'Nepal',
        nr: 'Nauru',
        nu: 'Niue',
        nz: 'New Zealand',
        om: 'Oman',
        pa: 'Panama',
        pe: 'Peru',
        pf: 'French Polynesia',
        pg: 'Papua New Guinea',
        ph: 'Philippines',
        pk: 'Pakistan',
        pl: 'Poland',
        pm: 'Saint Pierre and Miquelon',
        pn: 'Pitcairn',
        pr: 'Puerto Rico',
        ps: 'Palestinian Territory',
        pt: 'Portugal',
        pw: 'Palau',
        py: 'Paraguay',
        qa: 'Qatar',
        re: 'Reunion',
        ro: 'Romania',
        rs: 'Serbia',
        ru: 'Russian Federation',
        rw: 'Rwanda',
        sa: 'Saudi Arabia',
        sb: 'Solomon Islands',
        sc: 'Seychelles',
        sd: 'Sudan',
        se: 'Sweden',
        sg: 'Singapore',
        sh: 'Saint Helena',
        si: 'Slovenia',
        sj: 'Svalbard and Jan Mayen',
        sk: 'Slovakia',
        sl: 'Sierra Leone',
        sm: 'San Marino',
        sn: 'Senegal',
        so: 'Somalia',
        sr: 'Suriname',
        ss: 'South Sudan',
        st: 'Sao Tome and Principe',
        sv: 'El Salvador',
        sx: 'Sint Maarten',
        sy: 'Syrian Arab Republic',
        sz: 'Swaziland',
        tc: 'Turks and Caicos Islands',
        td: 'Chad',
        tf: 'French Southern Territories',
        tg: 'Togo',
        th: 'Thailand',
        tj: 'Tajikistan',
        tk: 'Tokelau',
        tl: 'Timor-Leste',
        tm: 'Turkmenistan',
        tn: 'Tunisia',
        to: 'Tonga',
        tr: 'Turkey',
        tt: 'Trinidad and Tobago',
        tv: 'Tuvalu',
        tw: 'Taiwan',
        tz: 'Tanzania, United Republic of',
        ua: 'Ukraine',
        ug: 'Uganda',
        um: 'United States Minor Outlying Islands',
        us: 'United States',
        uy: 'Uruguay',
        uz: 'Uzbekistan',
        va: 'Holy See (Vatican City State)',
        vc: 'Saint Vincent and the Grenadines',
        ve: 'Venezuela',
        vg: 'Virgin Islands, British',
        vi: 'Virgin Islands, U.S.',
        vn: 'Vietnam',
        vu: 'Vanuatu',
        wf: 'Wallis and Futuna',
        ws: 'Samoa',
        ye: 'Yemen',
        yt: 'Mayotte',
        za: 'South Africa',
        zm: 'Zambia',
        zw: 'Zimbabwe'
    },
    breadcrumbCountries: [
        {geolocation: 'ad', name: 'Andorra'},
        {geolocation: 'ae', name: 'United Arab Emirates'},
        {geolocation: 'af', name: 'Afghanistan'},
        {geolocation: 'ag', name: 'Antigua and Barbuda'},
        {geolocation: 'ai', name: 'Anguilla'},
        {geolocation: 'al', name: 'Albania'},
        {geolocation: 'am', name: 'Armenia'},
        {geolocation: 'ao', name: 'Angola'},
        {geolocation: 'ap', name: 'Asia/Pacific Region'},
        {geolocation: 'aq', name: 'Antarctica'},
        {geolocation: 'ar', name: 'Argentina'},
        {geolocation: 'as', name: 'American Samoa'},
        {geolocation: 'at', name: 'Austria'},
        {geolocation: 'au', name: 'Australia'},
        {geolocation: 'aw', name: 'Aruba'},
        {geolocation: 'ax', name: 'Aland Islands'},
        {geolocation: 'az', name: 'Azerbaijan'},
        {geolocation: 'ba', name: 'Bosnia and Herzegovina'},
        {geolocation: 'bb', name: 'Barbados'},
        {geolocation: 'bd', name: 'Bangladesh'},
        {geolocation: 'be', name: 'Belgium'},
        {geolocation: 'bf', name: 'Burkina Faso'},
        {geolocation: 'bg', name: 'Bulgaria'},
        {geolocation: 'bh', name: 'Bahrain'},
        {geolocation: 'bi', name: 'Burundi'},
        {geolocation: 'bj', name: 'Benin'},
        {geolocation: 'bl', name: 'Saint Bartelemey'},
        {geolocation: 'bm', name: 'Bermuda'},
        {geolocation: 'bn', name: 'Brunei Darussalam'},
        {geolocation: 'bo', name: 'Bolivia'},
        {geolocation: 'bq', name: 'Bonaire, Saint Eustatius and Saba'},
        {geolocation: 'br', name: 'Brazil'},
        {geolocation: 'bs', name: 'Bahamas'},
        {geolocation: 'bt', name: 'Bhutan'},
        {geolocation: 'bv', name: 'Bouvet Island'},
        {geolocation: 'bw', name: 'Botswana'},
        {geolocation: 'by', name: 'Belarus'},
        {geolocation: 'bz', name: 'Belize'},
        {geolocation: 'ca', name: 'Canada'},
        {geolocation: 'cc', name: 'Cocos (Keeling) Islands'},
        {geolocation: 'cd', name: 'Congo, The Democratic Republic of the'},
        {geolocation: 'cf', name: 'Central African Republic'},
        {geolocation: 'cg', name: 'Congo'},
        {geolocation: 'ch', name: 'Switzerland'},
        {geolocation: 'ci', name: "Cote d'Ivoire"},
        {geolocation: 'ck', name: 'Cook Islands'},
        {geolocation: 'cl', name: 'Chile'},
        {geolocation: 'cm', name: 'Cameroon'},
        {geolocation: 'cn', name: 'China'},
        {geolocation: 'co', name: 'Colombia'},
        {geolocation: 'cr', name: 'Costa Rica'},
        {geolocation: 'cu', name: 'Cuba'},
        {geolocation: 'cv', name: 'Cape Verde'},
        {geolocation: 'cw', name: 'Curacao'},
        {geolocation: 'cx', name: 'Christmas Island'},
        {geolocation: 'cy', name: 'Cyprus'},
        {geolocation: 'cz', name: 'Czech Republic'},
        {geolocation: 'de', name: 'Germany'},
        {geolocation: 'dj', name: 'Djibouti'},
        {geolocation: 'dk', name: 'Denmark'},
        {geolocation: 'dm', name: 'Dominica'},
        {geolocation: 'do', name: 'Dominican Republic'},
        {geolocation: 'dz', name: 'Algeria'},
        {geolocation: 'ec', name: 'Ecuador'},
        {geolocation: 'ee', name: 'Estonia'},
        {geolocation: 'eg', name: 'Egypt'},
        {geolocation: 'eh', name: 'Western Sahara'},
        {geolocation: 'er', name: 'Eritrea'},
        {geolocation: 'es', name: 'Spain'},
        {geolocation: 'et', name: 'Ethiopia'},
        {geolocation: 'eu', name: 'Europe'},
        {geolocation: 'fi', name: 'Finland'},
        {geolocation: 'fj', name: 'Fiji'},
        {geolocation: 'fk', name: 'Falkland Islands (Malvinas)'},
        {geolocation: 'fm', name: 'Micronesia, Federated States of'},
        {geolocation: 'fo', name: 'Faroe Islands'},
        {geolocation: 'fr', name: 'France'},
        {geolocation: 'ga', name: 'Gabon'},
        {geolocation: 'gb', name: 'United Kingdom'},
        {geolocation: 'gd', name: 'Grenada'},
        {geolocation: 'ge', name: 'Georgia'},
        {geolocation: 'gf', name: 'French Guiana'},
        {geolocation: 'gg', name: 'Guernsey'},
        {geolocation: 'gh', name: 'Ghana'},
        {geolocation: 'gi', name: 'Gibraltar'},
        {geolocation: 'gl', name: 'Greenland'},
        {geolocation: 'gm', name: 'Gambia'},
        {geolocation: 'gn', name: 'Guinea'},
        {geolocation: 'gp', name: 'Guadeloupe'},
        {geolocation: 'gq', name: 'Equatorial Guinea'},
        {geolocation: 'gr', name: 'Greece'},
        {geolocation: 'gs', name: 'South Georgia and the South Sandwich Islands'},
        {geolocation: 'gt', name: 'Guatemala'},
        {geolocation: 'gu', name: 'Guam'},
        {geolocation: 'gw', name: 'Guinea-Bissau'},
        {geolocation: 'gy', name: 'Guyana'},
        {geolocation: 'hk', name: 'Hong Kong'},
        {geolocation: 'hm', name: 'Heard Island and McDonald Islands'},
        {geolocation: 'hn', name: 'Honduras'},
        {geolocation: 'hr', name: 'Croatia'},
        {geolocation: 'ht', name: 'Haiti'},
        {geolocation: 'hu', name: 'Hungary'},
        {geolocation: 'id', name: 'Indonesia'},
        {geolocation: 'ie', name: 'Ireland'},
        {geolocation: 'il', name: 'Israel'},
        {geolocation: 'im', name: 'Isle of Man'},
        {geolocation: 'in', name: 'India'},
        {geolocation: 'io', name: 'British Indian Ocean Territory'},
        {geolocation: 'iq', name: 'Iraq'},
        {geolocation: 'ir', name: 'Iran, Islamic Republic of'},
        {geolocation: 'is', name: 'Iceland'},
        {geolocation: 'it', name: 'Italy'},
        {geolocation: 'je', name: 'Jersey'},
        {geolocation: 'jm', name: 'Jamaica'},
        {geolocation: 'jo', name: 'Jordan'},
        {geolocation: 'jp', name: 'Japan'},
        {geolocation: 'ke', name: 'Kenya'},
        {geolocation: 'kg', name: 'Kyrgyzstan'},
        {geolocation: 'kh', name: 'Cambodia'},
        {geolocation: 'ki', name: 'Kiribati'},
        {geolocation: 'km', name: 'Comoros'},
        {geolocation: 'kn', name: 'Saint Kitts and Nevis'},
        {geolocation: 'kr', name: 'South Korea'},
        {geolocation: 'kw', name: 'Kuwait'},
        {geolocation: 'ky', name: 'Cayman Islands'},
        {geolocation: 'kz', name: 'Kazakhstan'},
        {geolocation: 'la', name: "Lao People's Democratic Republic"},
        {geolocation: 'lb', name: 'Lebanon'},
        {geolocation: 'lc', name: 'Saint Lucia'},
        {geolocation: 'li', name: 'Liechtenstein'},
        {geolocation: 'lk', name: 'Sri Lanka'},
        {geolocation: 'lr', name: 'Liberia'},
        {geolocation: 'ls', name: 'Lesotho'},
        {geolocation: 'lt', name: 'Lithuania'},
        {geolocation: 'lu', name: 'Luxembourg'},
        {geolocation: 'lv', name: 'Latvia'},
        {geolocation: 'ly', name: 'Libyan Arab Jamahiriya'},
        {geolocation: 'ma', name: 'Morocco'},
        {geolocation: 'mc', name: 'Monaco'},
        {geolocation: 'md', name: 'Moldova, Republic of'},
        {geolocation: 'me', name: 'Montenegro'},
        {geolocation: 'mf', name: 'Saint Martin'},
        {geolocation: 'mg', name: 'Madagascar'},
        {geolocation: 'mh', name: 'Marshall Islands'},
        {geolocation: 'mk', name: 'Macedonia'},
        {geolocation: 'ml', name: 'Mali'},
        {geolocation: 'mm', name: 'Myanmar'},
        {geolocation: 'mn', name: 'Mongolia'},
        {geolocation: 'mo', name: 'Macao'},
        {geolocation: 'mp', name: 'Northern Mariana Islands'},
        {geolocation: 'mq', name: 'Martinique'},
        {geolocation: 'mr', name: 'Mauritania'},
        {geolocation: 'ms', name: 'Montserrat'},
        {geolocation: 'mt', name: 'Malta'},
        {geolocation: 'mu', name: 'Mauritius'},
        {geolocation: 'mv', name: 'Maldives'},
        {geolocation: 'mw', name: 'Malawi'},
        {geolocation: 'mx', name: 'Mexico'},
        {geolocation: 'my', name: 'Malaysia'},
        {geolocation: 'mz', name: 'Mozambique'},
        {geolocation: 'na', name: 'Namibia'},
        {geolocation: 'nc', name: 'New Caledonia'},
        {geolocation: 'ne', name: 'Niger'},
        {geolocation: 'nf', name: 'Norfolk Island'},
        {geolocation: 'ng', name: 'Nigeria'},
        {geolocation: 'ni', name: 'Nicaragua'},
        {geolocation: 'nl', name: 'Netherlands'},
        {geolocation: 'no', name: 'Norway'},
        {geolocation: 'np', name: 'Nepal'},
        {geolocation: 'nr', name: 'Nauru'},
        {geolocation: 'nu', name: 'Niue'},
        {geolocation: 'nz', name: 'New Zealand'},
        {geolocation: 'om', name: 'Oman'},
        {geolocation: 'pa', name: 'Panama'},
        {geolocation: 'pe', name: 'Peru'},
        {geolocation: 'pf', name: 'French Polynesia'},
        {geolocation: 'pg', name: 'Papua New Guinea'},
        {geolocation: 'ph', name: 'Philippines'},
        {geolocation: 'pk', name: 'Pakistan'},
        {geolocation: 'pl', name: 'Poland'},
        {geolocation: 'pm', name: 'Saint Pierre and Miquelon'},
        {geolocation: 'pn', name: 'Pitcairn'},
        {geolocation: 'pr', name: 'Puerto Rico'},
        {geolocation: 'ps', name: 'Palestinian Territory'},
        {geolocation: 'pt', name: 'Portugal'},
        {geolocation: 'pw', name: 'Palau'},
        {geolocation: 'py', name: 'Paraguay'},
        {geolocation: 'qa', name: 'Qatar'},
        {geolocation: 're', name: 'Reunion'},
        {geolocation: 'ro', name: 'Romania'},
        {geolocation: 'rs', name: 'Serbia'},
        {geolocation: 'ru', name: 'Russian Federation'},
        {geolocation: 'rw', name: 'Rwanda'},
        {geolocation: 'sa', name: 'Saudi Arabia'},
        {geolocation: 'sb', name: 'Solomon Islands'},
        {geolocation: 'sc', name: 'Seychelles'},
        {geolocation: 'sd', name: 'Sudan'},
        {geolocation: 'se', name: 'Sweden'},
        {geolocation: 'sg', name: 'Singapore'},
        {geolocation: 'sh', name: 'Saint Helena'},
        {geolocation: 'si', name: 'Slovenia'},
        {geolocation: 'sj', name: 'Svalbard and Jan Mayen'},
        {geolocation: 'sk', name: 'Slovakia'},
        {geolocation: 'sl', name: 'Sierra Leone'},
        {geolocation: 'sm', name: 'San Marino'},
        {geolocation: 'sn', name: 'Senegal'},
        {geolocation: 'so', name: 'Somalia'},
        {geolocation: 'sr', name: 'Suriname'},
        {geolocation: 'ss', name: 'South Sudan'},
        {geolocation: 'st', name: 'Sao Tome and Principe'},
        {geolocation: 'sv', name: 'El Salvador'},
        {geolocation: 'sx', name: 'Sint Maarten'},
        {geolocation: 'sy', name: 'Syrian Arab Republic'},
        {geolocation: 'sz', name: 'Swaziland'},
        {geolocation: 'tc', name: 'Turks and Caicos Islands'},
        {geolocation: 'td', name: 'Chad'},
        {geolocation: 'tf', name: 'French Southern Territories'},
        {geolocation: 'tg', name: 'Togo'},
        {geolocation: 'th', name: 'Thailand'},
        {geolocation: 'tj', name: 'Tajikistan'},
        {geolocation: 'tk', name: 'Tokelau'},
        {geolocation: 'tl', name: 'Timor-Leste'},
        {geolocation: 'tm', name: 'Turkmenistan'},
        {geolocation: 'tn', name: 'Tunisia'},
        {geolocation: 'to', name: 'Tonga'},
        {geolocation: 'tr', name: 'Turkey'},
        {geolocation: 'tt', name: 'Trinidad and Tobago'},
        {geolocation: 'tv', name: 'Tuvalu'},
        {geolocation: 'tw', name: 'Taiwan'},
        {geolocation: 'tz', name: 'Tanzania, United Republic of'},
        {geolocation: 'ua', name: 'Ukraine'},
        {geolocation: 'ug', name: 'Uganda'},
        {geolocation: 'um', name: 'United States Minor Outlying Islands'},
        {geolocation: 'us', name: 'United States'},
        {geolocation: 'uy', name: 'Uruguay'},
        {geolocation: 'uz', name: 'Uzbekistan'},
        {geolocation: 'va', name: 'Holy See (Vatican City State)'},
        {geolocation: 'vc', name: 'Saint Vincent and the Grenadines'},
        {geolocation: 've', name: 'Venezuela'},
        {geolocation: 'vg', name: 'Virgin Islands, British'},
        {geolocation: 'vi', name: 'Virgin Islands, U.S.'},
        {geolocation: 'vn', name: 'Vietnam'},
        {geolocation: 'vu', name: 'Vanuatu'},
        {geolocation: 'wf', name: 'Wallis and Futuna'},
        {geolocation: 'ws', name: 'Samoa'},
        {geolocation: 'ye', name: 'Yemen'},
        {geolocation: 'yt', name: 'Mayotte'},
        {geolocation: 'za', name: 'South Africa'},
        {geolocation: 'zm', name: 'Zambia'},
        {geolocation: 'zw', name: 'Zimbabwe'}
    ]
}
